<?php

namespace Ilius\DemoWsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MRouteRepository extends EntityRepository
{
public function getMRoutes($order_by = array(), $offset = 0, $limit = 0) {
    //Create query builder for languages table
    $qb = $this->createQueryBuilder('m');
    //Show all if offset and limit not set, also show all when limit is 0
    if ((isset($offset)) && (isset($limit))) {
        if ($limit > 0) {
            $qb->setFirstResult($offset);
            $qb->setMaxResults($limit);
        }
        //else we want to display all items on one page
    }
    //Adding defined sorting parameters from variable into query
    if (isset($order_by)) {
        foreach ($order_by as $key => $value) {
            $qb->add('orderBy', 'l.' . $key . ' ' . $value);
        }
    }
    //Get our query
    $q = $qb->getQuery();
    //Return result
    return $q->getResult();
}
}
