<?php

namespace Ilius\DemoWsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointRepository extends EntityRepository
{
}
